### ISSUE TITLE
Can't install to Python3 in virtualenv

### ISSUE THREAD

**Issue by nazandr** [pypa/ssl#7]
```
Using cached ssl-1.16.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-gygom9j7/ssl/setup.py", line 33
        print 'looking for', f
                          ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/v_/0ccnntmx21j9fnj7jjhqvf5c0000gn/T/pip-build-gygom9j7/ssl/
```

I think it need some brackets, like this
`print( 'looking for', f)`
Or it doesn't support python3?

**Comment by sigmavirus24** [comment]
I'd doesn't support anything after Python 2.5. The repository is quite clear on that point.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Fennec78** [comment]
Can't install  pip install ssl on ubuntu 
[Errno 2] No such file or directory
